Repository HarvestHaven/TPOT-Toolbox, pull requests merged in 2019-08, with the labels that each got.

#29 Added a parentsUntil() to replace jQuery's
  src/shared/stores/wp-credentials.js
  src/shared/utilities/converter.js
  src/shared/utilities/jQueryHelpers.js
  src/shared/utilities/test.html
Labels: enhancement

#47 Pre-Alpha Restructuring
  package.json
  public/index.html
  src/apps/Editor/Draft.jsx
  src/apps/Editor/Editor.jsx
  src/apps/Editor/plugins/draft-js-link-decorators/index.jsx
  src/apps/Scribe/index.jsx
  src/apps/Scribe/views/LoadScreen.jsx
  src/apps/Toolbox/App.css
  src/apps/Toolbox/indexNew.jsx
  src/apps/Toolbox/views/Dashboard.jsx
  src/apps/Toolbox/views/RoutedModal.jsx
  src/apps/Toolbox/views/Shelf.jsx
  src/apps/Toolbox/views/Sidebar.jsx
  src/index.js
  src/shared/stores/editor.js
  src/shared/stores/indexNew.js
  src/shared/stores/scribe.js
  yarn.lock
Labels: bug, milestone

#48 No Display Hotfix
  public/_redirects
  src/apps/Toolbox/index.jsx
  src/apps/Toolbox/indexNew.jsx
  src/index.js
  src/shared/stores/index.js
  src/shared/stores/indexNew.js
  src/shared/stores/letters.js
  src/shared/stores/session.js
  src/templates/index.stories.jsx
Labels: bug
